import "./css/tailwind.css"

import "@fontsource-variable/work-sans/index.css"
import "@fontsource-variable/cabin/index.css"

import "froala-editor/css/froala_style.css"
import "./css/site/froala_custom.css"

import "./css/styles.css"

import "./css/site/header.css"
import "./css/site/footer.css"
import "./css/site/form.css"

import "./css/components/loading-indicator.css"
import "./css/components/title-image.css"
import "./css/components/privacy.css"
import "./css/components/button.css"
import "./css/components/section.css"
import "./css/components/text-with-images.css"
import "./css/components/text-with-cta.css"
import "./css/components/history-timeline.css"
import "./css/components/schutzkonzept.css"
import "./css/components/blog-posts.css"
import "./css/components/blog-post.css"
import "./css/components/person.css"
import "./css/components/category.css"
import "./css/components/search.css"
import "./css/components/contact-info.css"
import "./css/components/contact-form.css"
import "./css/components/cta.css"
import "./css/components/pagination.css"
import "./css/components/columns.css"
import "./css/components/slider.css"
import "./css/components/aktuelles.css"
import "./css/components/faq.css"
import "./css/components/media-archive.css"
import "./css/components/transitions.css"
